#!/usr/bin/env bash

set -e
BASE_DIR=$1


create_virtualenv() {
    cd ${BASE_DIR}
    virtualenv . 
    source bin/activate

    pip install -U pip 
    pip install -U distribute 

    deactivate 
    virtualenv --relocatable ${BASE_DIR}

} 

