#!/usr/bin/env bash

set -e

BASE_DIR=$1
FPM_COMMAND=$2
DEB_URL=$3

echo "BASE DIR $BASE_DIR"
echo "FPM $FPM_COMMAND"
echo "URL $DEB_URL"

mkdir -p ${BASE_DIR}/deb/data
cd ${BASE_DIR}/deb

wget $DEB_URL
ar -x `ls *.deb`
tar zxf data.tar.gz -C data/
rsync -av --exclude=usr/share/pyshared --exclude=usr/lib/python2.7 data/ ${BUILD_DIR}/${PACKAGE}/ 

mkdir -p control
tar zxf control.tar.gz -C control/
    

