#!/usr/bin/env bash

set -e
BASE_DIR=$1

cd ${BASE_DIR}
virtualenv . 
. bin/activate

pip install -U pip 
pip install -U distribute &>> $LOG

deactivate &>> $LOG
virtualenv --relocatable ${BASE_DIR} &>> $LOG

