#!/usr/bin/env bash

set -e

PACKAGE=$1
BASE_DIR=$2

echo $BASE_DIR
echo `pwd`
echo $PACKAGE

cd ${BASE_DIR}
echo `pwd`
. bin/activate
pip install ${PACKAGE} 
deactivate 
virtualenv --relocatable .


