#!/usr/bin/env bash

set -e

PACKAGE=$1
BASE_DIR=$2

echo " BASE_DIR is $BASE_DIR"
echo " CURRENT 1 `pwd` "
echo $PACKAGE

cd ${BASE_DIR}
echo " CURRENT 2 `pwd`"
. bin/activate
pip install ${PACKAGE} 
deactivate 
virtualenv --relocatable .


